export const fallbackData = {
  profile: {
    full_name: 'Bishnu Pokhrel',
    designation: 'Senior Web Developer',
    short_intro: 'Senior Web Developer specialized in Laravel, PHP, Vue.js, and Java.',
    bio: 'A passionate and versatile developer with a strong foundation in building seamless, end-to-end digital solutions. Experienced in scalable web applications, CMS platforms, CRM and POS systems, payment integrations, RESTful APIs, performance optimization, security workflows, and mentoring development teams. Professional experience includes Tyler Technologies, Codespider Technology, and Technorio Inc Pvt. Ltd.',
    email: 'bishnupokhrel.se@gmail.com',
    phone: '+1 641 819 2400',
    location: '10300 W Winston Ave, Baton Rouge, LA 70809',
    hero_image_url: 'https://media.licdn.com/dms/image/v2/D4E03AQG8mRS6tdazNw/profile-displayphoto-scale_400_400/B4EZuZ111kHEAg-/0/1767812587456?e=1781136000&v=beta&t=5c7qmZNa4S-C5UOUBAkJdPyePMrkc1Ohod8x-jvHZHs',
    profile_image_url: 'https://media.licdn.com/dms/image/v2/D4E03AQG8mRS6tdazNw/profile-displayphoto-scale_400_400/B4EZuZ111kHEAg-/0/1767812587456?e=1781136000&v=beta&t=5c7qmZNa4S-C5UOUBAkJdPyePMrkc1Ohod8x-jvHZHs',
    cv_url: 'https://bishnupokhrel.netlify.app/resume/Bishnu-Pokhrel-Resume.pdf',
    social_links: {
      github: 'https://github.com/Bishnupkl',
      linkedin: 'https://linkedin.com/in/20nupokhrel',
      twitter: 'https://twitter.com/20nu_pokharel',
    },
  },
  skills: [
    { name: 'PHP', percentage: 95, category: 'Languages' },
    { name: 'JavaScript', percentage: 90, category: 'Languages' },
    { name: 'TypeScript', percentage: 82, category: 'Languages' },
    { name: 'Java', percentage: 78, category: 'Languages' },
    { name: 'Laravel', percentage: 95, category: 'Frameworks' },
    { name: 'Vue.js', percentage: 90, category: 'Frameworks' },
    { name: 'React', percentage: 84, category: 'Frameworks' },
    { name: 'Angular', percentage: 78, category: 'Frameworks' },
    { name: 'WordPress', percentage: 86, category: 'Frameworks' },
    { name: 'Ecommerce', percentage: 90, category: 'Domains' },
    { name: 'Education', percentage: 86, category: 'Domains' },
    { name: 'Health', percentage: 80, category: 'Domains' },
    { name: 'Social Media', percentage: 82, category: 'Domains' },
    { name: 'Fintech', percentage: 84, category: 'Domains' },
  ],
  services: [
    { title: 'Laravel Web Development', icon: 'Code', description: 'Custom Laravel applications, APIs, admin panels, CRM systems, POS systems, and secure payment integrations.' },
    { title: 'Vue.js Frontend Development', icon: 'Monitor', description: 'Responsive Vue.js interfaces, dashboards, and interactive web applications.' },
    { title: 'API & Backend Architecture', icon: 'Layers', description: 'Scalable RESTful APIs, data modeling, authentication workflows, and third-party integrations.' },
    { title: 'Ecommerce Development', icon: 'Gauge', description: 'Shopping platforms, payment processing with PayPal and Stripe, and performance-focused commerce workflows.' },
    { title: 'WordPress Customization', icon: 'Lightbulb', description: 'Custom WordPress solutions for business websites, performance improvements, and user engagement.' },
    { title: 'Technical Mentoring', icon: 'Smartphone', description: 'Code reviews, junior developer mentoring, and practical engineering best practices.' },
  ],
  projects: [
    { title: 'Baldev Sir', slug: 'baldev-sir', description: 'Online teaching center for Class 11 and Class 12 account courses, with student registration, login, recent classes, notices, and video lesson access.', category: 'Education Platform', technologies: ['Laravel', 'PHP', 'MySQL', 'Video Learning'], live_url: 'https://baldevsir.com', image_url: 'https://baldevsir.com/images/1779720130.png' },
    { title: 'SwimSeeker', slug: 'swim-seeker', description: 'Fishing discovery and community platform connecting individuals and businesses with fishing experiences, locations, guides, and outdoor activity workflows.', category: 'Community Platform', technologies: ['Laravel', 'PHP', 'Marketplace', 'Frontend'], live_url: 'https://swimseeker.com', image_url: 'https://swimseeker.com/storage/uploads/assets/information/1748166762.jpeg' },
    { title: 'Flash Sale Nepal', slug: 'flash-sale-nepal', description: 'Ecommerce and flash-sale platform for Nepal-based online shopping.', category: 'Ecommerce', technologies: ['Laravel', 'PHP', 'Payment Integration'], live_url: 'https://flashsalenepal.com', image_url: 'https://s.wordpress.com/mshots/v1/https%3A%2F%2Fflashsalenepal.com?w=900' },
    { title: 'SummitClimb', slug: 'summit-climb', description: 'Expedition and trekking website covering Everest, Nepal, Tibet, Karakoram, training climbs, trekking peaks, trip details, applications, and expedition content.', category: 'Adventure Travel', technologies: ['PHP', 'WordPress', 'Frontend', 'Content Management'], live_url: 'https://summitclimb.com', image_url: 'https://www.summitclimb.com/images/sliders/slider1588593625_summitclimb-expedition.jpg' },
    { title: 'IME London', slug: 'ime-london', description: 'Business website for IME London with customer-facing service information.', category: 'Business Website', technologies: ['PHP', 'Frontend', 'CMS'], live_url: 'https://imelondon.co.uk', image_url: 'https://s.wordpress.com/mshots/v1/https%3A%2F%2Fimelondon.co.uk?w=900' },
    { title: 'Kiddies', slug: 'kiddies', description: 'Children-focused website and digital platform work for Kiddies.com.', category: 'Business Website', technologies: ['PHP', 'Frontend', 'CMS'], live_url: 'https://kiddies.com', image_url: 'https://s.wordpress.com/mshots/v1/https%3A%2F%2Fkiddies.com?w=900' },
    { title: 'Online Entrance Examination', slug: 'online-entrance-examination', description: 'Final year online entrance examination system.', category: 'Education', technologies: ['PHP', 'MySQL'], github_url: 'https://github.com/Bishnupkl/Online-Entrance-Examination', image_url: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=900&q=80' },
    { title: 'BulksparrowSMSLaravel', slug: 'bulksparrowsmslaravel', description: 'Laravel integration project for Bulksparrow SMS workflows.', category: 'Messaging', technologies: ['Laravel', 'SMS API'], github_url: 'https://github.com/Bishnupkl/BulksparrowSMSLaravel', image_url: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=900&q=80' },
    { title: 'LunchHourManagementSystem', slug: 'lunchhourmanagementsystem', description: 'Lunch hour management system for a single office.', category: 'Office Management', technologies: ['HTML', 'PHP'], github_url: 'https://github.com/Bishnupkl/LunchHourManagementSystem', image_url: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=900&q=80' },
  ],
  testimonials: [
    {
      client_name: 'Professional Summary',
      client_role: 'Bishnu Pokhrel',
      feedback: 'I offer more than 6 years of experience with web development and a proven track record of meeting aggressive goals. I am comfortable communicating with technical and non-technical employees to complete projects and achieve organizational goals.',
      rating: 5,
      client_image_url: 'https://media.licdn.com/dms/image/v2/D4E03AQG8mRS6tdazNw/profile-displayphoto-scale_400_400/B4EZuZ111kHEAg-/0/1767812587456?e=1781136000&v=beta&t=5c7qmZNa4S-C5UOUBAkJdPyePMrkc1Ohod8x-jvHZHs',
    },
  ],
  settings: {
    site_logo: '20nu',
    footer_text: 'Bishnu Pokhrel - Senior Web Developer specialized in Laravel, PHP, Vue.js, and Java.',
    seo_title: 'Bishnu Pokhrel | Senior Web Developer',
    seo_description: 'Portfolio of Bishnu Pokhrel, a senior web developer specializing in Laravel, PHP, Vue.js, Java, ecommerce, education, health, social media, and fintech solutions.',
    maintenance_mode: '0',
    github_url: 'https://github.com/Bishnupkl',
    linkedin_url: 'https://linkedin.com/in/20nupokhrel',
    twitter_url: 'https://twitter.com/20nu_pokharel',
    experience_years: '8+',
    experience_heading: 'Senior engineer building Laravel, PHP, and full stack web platforms',
    typing_titles: [
      'Senior Software Engineer',
      'Tech Lead',
      'Laravel Architect',
      'Senior PHP Developer',
      'Senior Full Stack Developer',
      'Senior Web Developer',
    ],
    hero_highlights: [
      'Laravel API architecture',
      'Vue.js frontend delivery',
      'Admin dashboards and CMS',
      'Payment and third-party integrations',
    ],
    experience_companies: [
      { name: 'Tyler Technologies', relationship: 'Main Experience' },
      { name: 'Codespider Technology', relationship: 'Main Experience' },
      { name: 'Technorio Inc', relationship: 'Main Experience' },
      { name: 'BipointX', relationship: 'Collaborations' },
      { name: 'Mutex Tech', relationship: 'Collaborations' },
      { name: 'Nepal Creative Tech', relationship: 'Collaborations' },
    ],
    experience_highlights: [
      { title: 'Senior Software Engineering', icon: 'Code2', dark: true },
      { title: 'Laravel Architecture', icon: 'Layers', dark: false },
      { title: 'Full Stack Delivery', icon: 'Monitor', dark: false },
    ],
    brand_companies: [
      { name: 'Tyler Technologies', domain: 'tylertech.com', url: 'https://www.tylertech.com/', relationship: 'Main Experience' },
      { name: 'Codespider Technology', domain: 'codespider.co.uk', url: 'https://codespider.co.uk/', relationship: 'Main Experience' },
      { name: 'Technorio Inc', domain: 'technorio.com', url: 'https://technorio.com/', relationship: 'Main Experience' },
      { name: 'BipointX', domain: 'bitpointx.com.au', url: 'https://www.bitpointx.com.au/', relationship: 'Collaboration' },
      { name: 'Mutex Tech', domain: 'mutextech.com.np', url: 'https://mutextech.com.np/', relationship: 'Collaboration' },
      { name: 'Nepal Creative Tech', domain: 'nctsoft.com.np', url: 'https://www.nctsoft.com.np/', relationship: 'Collaboration' },
    ],
    portfolio_stats: [
      { label: 'Years Experience', value: '8+', icon: 'Award', description: 'Laravel, PHP, Vue.js, and production web systems.' },
      { label: 'Companies', value: '6', icon: 'BriefcaseBusiness', description: 'Professional and project-based engineering teams.' },
      { label: 'Live Projects', value: '6+', icon: 'Rocket', description: 'Business, education, ecommerce, and service platforms.' },
      { label: 'Core Skills', value: '14', icon: 'Code2', description: 'Backend, frontend, CMS, API, and cloud workflows.' },
    ],
    professional_experiences: [
      {
        company: 'Tyler Technologies',
        role: 'Senior Software Engineer',
        period: 'June 2025 - Present',
        mode: 'Hybrid',
        summary: 'Designed and implemented scalable core components for Enterprise Supervision CMS, including case data, risk assessments, integrations, and performance tuning on AWS GovCloud.',
      },
      {
        company: 'Codespider Technology',
        role: 'Software Engineer',
        period: 'April 2019 - May 2024',
        mode: 'Remote',
        summary: 'Led architecture and database design for scalable web applications, Laravel payment gateways, Express APIs, OAuth/JWT security, and code review mentoring.',
      },
      {
        company: 'Technorio Inc',
        role: 'Web Developer',
        period: 'June 2018 - March 2019',
        mode: 'On-site',
        summary: 'Built CRM, POS, WordPress, and JavaScript web applications with Laravel and Vue.js, improving operations and frontend performance.',
      },
      {
        company: 'BipointX',
        role: 'Full Stack Developer',
        period: 'Project Collaboration',
        mode: 'Remote',
        summary: 'Delivered full stack PHP/Laravel and frontend work for business-facing web platforms.',
      },
      {
        company: 'Mutex Tech',
        role: 'Web Developer',
        period: 'Project Collaboration',
        mode: 'Remote',
        summary: 'Worked on backend/frontend implementation for production websites and service workflows.',
      },
      {
        company: 'Nepal Creative Tech',
        role: 'Web Developer',
        period: 'Project Collaboration',
        mode: 'Remote',
        summary: 'Supported custom web development and CMS-driven business websites.',
      },
    ],
    education_items: [
      {
        school: 'Maharishi International University',
        degree: 'Master of Science in Computer Science',
        period: '2024 - 2026',
        summary: 'Key courses: Algorithms, Web Application Programming, Modern Web Applications, and Cloud Computing.',
      },
      {
        school: 'Tribhuvan University',
        degree: 'Bachelor of Science in Computer Science',
        period: '2014 - 2018',
        summary: 'Key courses: Object Oriented Programming, Web Application Programming, Software Engineering, and Design and Analysis of Algorithm.',
      },
    ],
    work_process: [
      {
        title: 'Discover',
        icon: 'Search',
        description: 'Clarify business goals, workflows, user roles, data needs, and the fastest path to a useful first release.',
      },
      {
        title: 'Design',
        icon: 'PenTool',
        description: 'Plan the API contracts, database structure, admin screens, frontend states, and deployment approach.',
      },
      {
        title: 'Build',
        icon: 'Code2',
        description: 'Implement Laravel, Vue, integrations, authentication, file uploads, and clean reusable components.',
      },
      {
        title: 'Launch',
        icon: 'Rocket',
        description: 'Test production behavior, optimize performance, configure hosting, and prepare the system for real users.',
      },
    ],
  },
};
